# Generated by Django 4.2.18 on 2025-02-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purposeapp', '0001_initial'),
        ('incomeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='income',
            name='purpose_detail',
        ),
        migrations.AddField(
            model_name='income',
            name='purpose_details',
            field=models.ManyToManyField(blank=True, to='purposeapp.purposedetail'),
        ),
        migrations.AlterField(
            model_name='income',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purposeapp.purpose'),
        ),
    ]
