# Generated by Django 4.2.18 on 2025-02-03 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('incomeapp', '0002_remove_income_notes_remove_income_purpose_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
        migrations.AddField(
            model_name='income',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
