# Generated by Django 4.2.18 on 2025-02-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationapp', '0001_initial'),
        ('incomeapp', '0003_remove_income_date_income_date_time_income_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='related_party',
        ),
        migrations.AddField(
            model_name='income',
            name='related_parties',
            field=models.ManyToManyField(blank=True, to='locationapp.relatedparty'),
        ),
        migrations.AlterField(
            model_name='income',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locationapp.location'),
        ),
    ]
