# Generated by Django 4.2.18 on 2025-02-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
        ('incomeapp', '0004_remove_income_related_party_income_related_parties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='status',
        ),
        migrations.AddField(
            model_name='income',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentapp.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentapp.paymentmethod'),
        ),
    ]
