# Generated by Django 4.2.18 on 2025-02-03 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
        ('locationapp', '0001_initial'),
        ('expenseapp', '0003_remove_expense_date_expense_date_time_expense_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='related_party',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentapp.paymentstatus'),
        ),
        migrations.AddField(
            model_name='expense',
            name='related_parties',
            field=models.ManyToManyField(blank=True, to='locationapp.relatedparty'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locationapp.location'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentapp.paymentmethod'),
        ),
    ]
