# Generated by Django 4.2.18 on 2025-02-03 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='date',
        ),
        migrations.AddField(
            model_name='balance',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
