# Generated by Django 4.2.18 on 2025-02-03 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balanceapp', '0002_remove_balance_date_balance_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balance',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='balance',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
