name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set environment variables
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> $GITHUB_ENV
        echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> $GITHUB_ENV
        echo "PGUSER=${{ secrets.PGUSER }}" >> $GITHUB_ENV
        echo "RAILWAY_TCP_PROXY_DOMAIN=${{ secrets.RAILWAY_TCP_PROXY_DOMAIN }}" >> $GITHUB_ENV
        echo "RAILWAY_TCP_PROXY_PORT=${{ secrets.RAILWAY_TCP_PROXY_PORT }}" >> $GITHUB_ENV
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGUSER: ${{ secrets.PGUSER }}
        RAILWAY_TCP_PROXY_DOMAIN: ${{ secrets.RAILWAY_TCP_PROXY_DOMAIN }}
        RAILWAY_TCP_PROXY_PORT: ${{ secrets.RAILWAY_TCP_PROXY_PORT }}
